name: raschetka_dev

services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
