# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

name: raschetka

services:
  pg:
    container_name: raschetka_pg
    image: postgres:15-alpine
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:5433:5432"
    logging:
      driver: none
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s
    volumes:
      - pgdata:/var/lib/postgresql/data

  dockersocket:
    image: tecnativa/docker-socket-proxy:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1

  app:
    container_name: raschetka
    image: raschetka:latest
    build:
      context: .
    env_file: .env
    ports:
      - "127.0.0.1:${APP_PORT}:${APP_PORT}"
    logging:
      driver: local
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - appdata:/app/storage
      - fail2bandata:/var/lib/fail2ban
    depends_on:
      pg:
        condition: service_healthy
      dockersocket:
        condition: service_started

volumes:
  pgdata:
  appdata:
  fail2bandata:
