[supervisord]
nodaemon=true
loglevel=critical
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord/supervisord.pid

[program:nginx]
command=/bin/sh -lc "envsubst '\$APP_PORT' < /etc/nginx/http.d/default.conf.template > /etc/nginx/http.d/default.conf && exec /usr/sbin/nginx -g 'daemon off; pid /run/nginx/nginx.pid; error_log /dev/stderr warn;'"
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
stopsignal=QUIT

[program:node]
directory=/app
command=/bin/sh -lc "PRISMA_HIDE_UPDATE_MESSAGE=1 npx prisma migrate deploy && node app/index.js"
environment=NODE_ENV="production"
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true
stopsignal=TERM

[program:fail2ban]
command=/usr/bin/fail2ban-server -xf start
autorestart=true
priority=30
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true
stopsignal=TERM

