[Definition]
failregex = ^<HOST> - - \[.*\] "\S+\s/(?:\.env|\.git|env)\b[^\s"]*" (?:403|404)
            ^<HOST> - - \[.*\] "\S+\s/(?:api/config/.*|.*\btsconfig\.json)\b[^\s"]*" (?:403|404)
            ^<HOST> - - \[.*\] "\S+\s/(?:api_keys(?:/|%%2[Ff]).*)[^\s"]*" (?:403|404)
            ^<HOST> - - \[.*\] "\S+\s/(?:storage/(?:logs(?:/|%%2[Ff]).*|framework/cache/data(?:/|%%2[Ff]).*))[^\s"]*" (?:403|404)
            ^<HOST> - - \[.*\] "\S+\s/(?:storage/(?:aws_keys\.json|sendgrid(?:_keys)?\.json|sendinblue(?:_keys)?\.json))\b[^\s"]*" (?:403|404)
            ^<HOST> - - \[.*\] "\S+\s/[^\s"]*\.log\b[^\s"]*" (?:403|404)
ignoreregex =
