[Definition]
failregex = ^<HOST> - - \[.*\] "\S+\s/(?:\.env(?:\.[^/"]*)?|\.git|env)[^"]*" [45]\d{2}
            ^<HOST> - - \[.*\] "\S+\s/(?:api/config/[^"]*tsconfig\.json)[^"]*" [45]\d{2}
            ^<HOST> - - \[.*\] "\S+\s/(?:api_keys(?:/|%%2[Ff])[^"]*)" [45]\d{2}
            ^<HOST> - - \[.*\] "\S+\s/(?:storage/(?:logs(?:/|%%2[Ff])[^"]*|framework/cache/data(?:/|%%2[Ff])[^"]*))" [45]\d{2}
            ^<HOST> - - \[.*\] "\S+\s/(?:storage/[^"]*\.(?:log|env|php))[^"]*" [45]\d{2}
            ^<HOST> - - \[.*\] "\S+\s/(?:storage/(?:aws_keys\.json|sendgrid(?:_keys)?\.json|sendinblue(?:_keys)?\.json))[^"]*" [45]\d{2}
ignoreregex =
