name: Build and deploy to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2. Устанавливаем Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Шаг 3. Собираем Docker-образ
      - name: Build Docker image
        run: |
          docker build -t raschetka .
          docker save -o raschetka.tar raschetka
          gzip raschetka.tar

      # Шаг 4. Устанавливаем SSH-ключ
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Шаг 5. Копируем архив с Docker-образом на сервер
      - name: Copy new app to external server
        run: |
          rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no" \
            raschetka.tar.gz docker-compose.yml \
            "${{ vars.EXTERNAL_SERVER_USER }}@${{ vars.EXTERNAL_SERVER_IP_ADDR }}:${{ vars.EXTERNAL_SERVER_DESTINATION }}/"

      # Шаг 6. Запускаем обновленный образ бота на сервере
      - name: Run new app on external server
        run: |
          ssh -t -o StrictHostKeyChecking=no ${{ vars.EXTERNAL_SERVER_USER }}@${{ vars.EXTERNAL_SERVER_IP_ADDR }} "bash -s" << 'EOF'
            set -euo pipefail

            cd ${{ vars.EXTERNAL_SERVER_DESTINATION }}

            OLD_ID=$(docker images --filter=reference='raschetka:latest' --format '{{.ID}}')
            gunzip raschetka.tar.gz
            docker load -i raschetka.tar
            rm raschetka.tar

            docker compose up -d --no-build

            if [ -n "$OLD_ID" ]; then docker rmi "$OLD_ID" --force; fi
          EOF

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()

    steps:
      # Единственный шаг: отправляем сообщение о деплое
      - name: Send telegram message about deploy
        run: |
          case "${{ needs.deploy.result }}" in
            success)   STATUS="✅ Успешный деплой" ;;
            cancelled) STATUS="⚪️ Деплой отменён" ;;
            *)         STATUS="❌ Деплой сломался" ;;
          esac

          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          TEXT="${STATUS}\n\n${RUN_URL}"

          curl -sS -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d disable_web_page_preview=true \
            --data-urlencode text="${TEXT}"
